#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Courier_Tracking_System")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoleMaster(RoleMaster instance);
    partial void UpdateRoleMaster(RoleMaster instance);
    partial void DeleteRoleMaster(RoleMaster instance);
    partial void InsertCts_User_Master(Cts_User_Master instance);
    partial void UpdateCts_User_Master(Cts_User_Master instance);
    partial void DeleteCts_User_Master(Cts_User_Master instance);
    partial void InsertCts_BranchMaster(Cts_BranchMaster instance);
    partial void UpdateCts_BranchMaster(Cts_BranchMaster instance);
    partial void DeleteCts_BranchMaster(Cts_BranchMaster instance);
    partial void InsertCts_Package(Cts_Package instance);
    partial void UpdateCts_Package(Cts_Package instance);
    partial void DeleteCts_Package(Cts_Package instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::DAL.Properties.Settings.Default.Courier_Tracking_SystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RoleMaster> RoleMasters
		{
			get
			{
				return this.GetTable<RoleMaster>();
			}
		}
		
		public System.Data.Linq.Table<Cts_User_Master> Cts_User_Masters
		{
			get
			{
				return this.GetTable<Cts_User_Master>();
			}
		}
		
		public System.Data.Linq.Table<Cts_BranchMaster> Cts_BranchMasters
		{
			get
			{
				return this.GetTable<Cts_BranchMaster>();
			}
		}
		
		public System.Data.Linq.Table<Cts_Package> Cts_Packages
		{
			get
			{
				return this.GetTable<Cts_Package>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoleMaster")]
	public partial class RoleMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _RoleDescription;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _CreatedBy;
		
		private System.Nullable<bool> _IsActive;
		
		private EntitySet<Cts_User_Master> _Cts_User_Masters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleDescriptionChanging(string value);
    partial void OnRoleDescriptionChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public RoleMaster()
		{
			this._Cts_User_Masters = new EntitySet<Cts_User_Master>(new Action<Cts_User_Master>(this.attach_Cts_User_Masters), new Action<Cts_User_Master>(this.detach_Cts_User_Masters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleDescription", DbType="VarChar(50)")]
		public string RoleDescription
		{
			get
			{
				return this._RoleDescription;
			}
			set
			{
				if ((this._RoleDescription != value))
				{
					this.OnRoleDescriptionChanging(value);
					this.SendPropertyChanging();
					this._RoleDescription = value;
					this.SendPropertyChanged("RoleDescription");
					this.OnRoleDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RoleMaster_Cts_User_Master", Storage="_Cts_User_Masters", ThisKey="RoleID", OtherKey="um_RoleId")]
		public EntitySet<Cts_User_Master> Cts_User_Masters
		{
			get
			{
				return this._Cts_User_Masters;
			}
			set
			{
				this._Cts_User_Masters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cts_User_Masters(Cts_User_Master entity)
		{
			this.SendPropertyChanging();
			entity.RoleMaster = this;
		}
		
		private void detach_Cts_User_Masters(Cts_User_Master entity)
		{
			this.SendPropertyChanging();
			entity.RoleMaster = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cts_User_Master")]
	public partial class Cts_User_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _um_id;
		
		private string _um_userId;
		
		private string _um_password;
		
		private string _um_firstName;
		
		private string _um_lastName;
		
		private string _um_gender;
		
		private string _um_contact;
		
		private string _um_emailId;
		
		private System.Nullable<bool> _um_isActive;
		
		private System.Nullable<long> _um_Salary;
		
		private string _um_Designation;
		
		private string _um_PerAddress;
		
		private string _um_CorAddress;
		
		private System.Nullable<System.DateTime> _um_created_On;
		
		private string _um_created_by;
		
		private System.Nullable<System.DateTime> _um_IsApprovedOn;
		
		private string _um_IsApprovedBy;
		
		private System.Nullable<int> _um_RoleId;
		
		private string _um_emp_cid;
		
		private EntitySet<Cts_Package> _Cts_Packages;
		
		private EntityRef<RoleMaster> _RoleMaster;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onum_idChanging(int value);
    partial void Onum_idChanged();
    partial void Onum_userIdChanging(string value);
    partial void Onum_userIdChanged();
    partial void Onum_passwordChanging(string value);
    partial void Onum_passwordChanged();
    partial void Onum_firstNameChanging(string value);
    partial void Onum_firstNameChanged();
    partial void Onum_lastNameChanging(string value);
    partial void Onum_lastNameChanged();
    partial void Onum_genderChanging(string value);
    partial void Onum_genderChanged();
    partial void Onum_contactChanging(string value);
    partial void Onum_contactChanged();
    partial void Onum_emailIdChanging(string value);
    partial void Onum_emailIdChanged();
    partial void Onum_isActiveChanging(System.Nullable<bool> value);
    partial void Onum_isActiveChanged();
    partial void Onum_SalaryChanging(System.Nullable<long> value);
    partial void Onum_SalaryChanged();
    partial void Onum_DesignationChanging(string value);
    partial void Onum_DesignationChanged();
    partial void Onum_PerAddressChanging(string value);
    partial void Onum_PerAddressChanged();
    partial void Onum_CorAddressChanging(string value);
    partial void Onum_CorAddressChanged();
    partial void Onum_created_OnChanging(System.Nullable<System.DateTime> value);
    partial void Onum_created_OnChanged();
    partial void Onum_created_byChanging(string value);
    partial void Onum_created_byChanged();
    partial void Onum_IsApprovedOnChanging(System.Nullable<System.DateTime> value);
    partial void Onum_IsApprovedOnChanged();
    partial void Onum_IsApprovedByChanging(string value);
    partial void Onum_IsApprovedByChanged();
    partial void Onum_RoleIdChanging(System.Nullable<int> value);
    partial void Onum_RoleIdChanged();
    partial void Onum_emp_cidChanging(string value);
    partial void Onum_emp_cidChanged();
    #endregion
		
		public Cts_User_Master()
		{
			this._Cts_Packages = new EntitySet<Cts_Package>(new Action<Cts_Package>(this.attach_Cts_Packages), new Action<Cts_Package>(this.detach_Cts_Packages));
			this._RoleMaster = default(EntityRef<RoleMaster>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int um_id
		{
			get
			{
				return this._um_id;
			}
			set
			{
				if ((this._um_id != value))
				{
					this.Onum_idChanging(value);
					this.SendPropertyChanging();
					this._um_id = value;
					this.SendPropertyChanged("um_id");
					this.Onum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_userId", DbType="VarChar(15)")]
		public string um_userId
		{
			get
			{
				return this._um_userId;
			}
			set
			{
				if ((this._um_userId != value))
				{
					this.Onum_userIdChanging(value);
					this.SendPropertyChanging();
					this._um_userId = value;
					this.SendPropertyChanged("um_userId");
					this.Onum_userIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_password", DbType="VarChar(15)")]
		public string um_password
		{
			get
			{
				return this._um_password;
			}
			set
			{
				if ((this._um_password != value))
				{
					this.Onum_passwordChanging(value);
					this.SendPropertyChanging();
					this._um_password = value;
					this.SendPropertyChanged("um_password");
					this.Onum_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_firstName", DbType="VarChar(50)")]
		public string um_firstName
		{
			get
			{
				return this._um_firstName;
			}
			set
			{
				if ((this._um_firstName != value))
				{
					this.Onum_firstNameChanging(value);
					this.SendPropertyChanging();
					this._um_firstName = value;
					this.SendPropertyChanged("um_firstName");
					this.Onum_firstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_lastName", DbType="VarChar(50)")]
		public string um_lastName
		{
			get
			{
				return this._um_lastName;
			}
			set
			{
				if ((this._um_lastName != value))
				{
					this.Onum_lastNameChanging(value);
					this.SendPropertyChanging();
					this._um_lastName = value;
					this.SendPropertyChanged("um_lastName");
					this.Onum_lastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_gender", DbType="VarChar(6)")]
		public string um_gender
		{
			get
			{
				return this._um_gender;
			}
			set
			{
				if ((this._um_gender != value))
				{
					this.Onum_genderChanging(value);
					this.SendPropertyChanging();
					this._um_gender = value;
					this.SendPropertyChanged("um_gender");
					this.Onum_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_contact", DbType="VarChar(10)")]
		public string um_contact
		{
			get
			{
				return this._um_contact;
			}
			set
			{
				if ((this._um_contact != value))
				{
					this.Onum_contactChanging(value);
					this.SendPropertyChanging();
					this._um_contact = value;
					this.SendPropertyChanged("um_contact");
					this.Onum_contactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_emailId", DbType="VarChar(50)")]
		public string um_emailId
		{
			get
			{
				return this._um_emailId;
			}
			set
			{
				if ((this._um_emailId != value))
				{
					this.Onum_emailIdChanging(value);
					this.SendPropertyChanging();
					this._um_emailId = value;
					this.SendPropertyChanged("um_emailId");
					this.Onum_emailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_isActive", DbType="Bit")]
		public System.Nullable<bool> um_isActive
		{
			get
			{
				return this._um_isActive;
			}
			set
			{
				if ((this._um_isActive != value))
				{
					this.Onum_isActiveChanging(value);
					this.SendPropertyChanging();
					this._um_isActive = value;
					this.SendPropertyChanged("um_isActive");
					this.Onum_isActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_Salary", DbType="BigInt")]
		public System.Nullable<long> um_Salary
		{
			get
			{
				return this._um_Salary;
			}
			set
			{
				if ((this._um_Salary != value))
				{
					this.Onum_SalaryChanging(value);
					this.SendPropertyChanging();
					this._um_Salary = value;
					this.SendPropertyChanged("um_Salary");
					this.Onum_SalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_Designation", DbType="VarChar(15)")]
		public string um_Designation
		{
			get
			{
				return this._um_Designation;
			}
			set
			{
				if ((this._um_Designation != value))
				{
					this.Onum_DesignationChanging(value);
					this.SendPropertyChanging();
					this._um_Designation = value;
					this.SendPropertyChanged("um_Designation");
					this.Onum_DesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_PerAddress", DbType="VarChar(100)")]
		public string um_PerAddress
		{
			get
			{
				return this._um_PerAddress;
			}
			set
			{
				if ((this._um_PerAddress != value))
				{
					this.Onum_PerAddressChanging(value);
					this.SendPropertyChanging();
					this._um_PerAddress = value;
					this.SendPropertyChanged("um_PerAddress");
					this.Onum_PerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_CorAddress", DbType="VarChar(100)")]
		public string um_CorAddress
		{
			get
			{
				return this._um_CorAddress;
			}
			set
			{
				if ((this._um_CorAddress != value))
				{
					this.Onum_CorAddressChanging(value);
					this.SendPropertyChanging();
					this._um_CorAddress = value;
					this.SendPropertyChanged("um_CorAddress");
					this.Onum_CorAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_created_On", DbType="Date")]
		public System.Nullable<System.DateTime> um_created_On
		{
			get
			{
				return this._um_created_On;
			}
			set
			{
				if ((this._um_created_On != value))
				{
					this.Onum_created_OnChanging(value);
					this.SendPropertyChanging();
					this._um_created_On = value;
					this.SendPropertyChanged("um_created_On");
					this.Onum_created_OnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_created_by", DbType="VarChar(20)")]
		public string um_created_by
		{
			get
			{
				return this._um_created_by;
			}
			set
			{
				if ((this._um_created_by != value))
				{
					this.Onum_created_byChanging(value);
					this.SendPropertyChanging();
					this._um_created_by = value;
					this.SendPropertyChanged("um_created_by");
					this.Onum_created_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_IsApprovedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> um_IsApprovedOn
		{
			get
			{
				return this._um_IsApprovedOn;
			}
			set
			{
				if ((this._um_IsApprovedOn != value))
				{
					this.Onum_IsApprovedOnChanging(value);
					this.SendPropertyChanging();
					this._um_IsApprovedOn = value;
					this.SendPropertyChanged("um_IsApprovedOn");
					this.Onum_IsApprovedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_IsApprovedBy", DbType="VarChar(50)")]
		public string um_IsApprovedBy
		{
			get
			{
				return this._um_IsApprovedBy;
			}
			set
			{
				if ((this._um_IsApprovedBy != value))
				{
					this.Onum_IsApprovedByChanging(value);
					this.SendPropertyChanging();
					this._um_IsApprovedBy = value;
					this.SendPropertyChanged("um_IsApprovedBy");
					this.Onum_IsApprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_RoleId", DbType="Int")]
		public System.Nullable<int> um_RoleId
		{
			get
			{
				return this._um_RoleId;
			}
			set
			{
				if ((this._um_RoleId != value))
				{
					if (this._RoleMaster.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onum_RoleIdChanging(value);
					this.SendPropertyChanging();
					this._um_RoleId = value;
					this.SendPropertyChanged("um_RoleId");
					this.Onum_RoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_um_emp_cid", AutoSync=AutoSync.Always, DbType="VarChar(37)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string um_emp_cid
		{
			get
			{
				return this._um_emp_cid;
			}
			set
			{
				if ((this._um_emp_cid != value))
				{
					this.Onum_emp_cidChanging(value);
					this.SendPropertyChanging();
					this._um_emp_cid = value;
					this.SendPropertyChanged("um_emp_cid");
					this.Onum_emp_cidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cts_User_Master_Cts_Package", Storage="_Cts_Packages", ThisKey="um_id", OtherKey="pk_Customer_id")]
		public EntitySet<Cts_Package> Cts_Packages
		{
			get
			{
				return this._Cts_Packages;
			}
			set
			{
				this._Cts_Packages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RoleMaster_Cts_User_Master", Storage="_RoleMaster", ThisKey="um_RoleId", OtherKey="RoleID", IsForeignKey=true)]
		public RoleMaster RoleMaster
		{
			get
			{
				return this._RoleMaster.Entity;
			}
			set
			{
				RoleMaster previousValue = this._RoleMaster.Entity;
				if (((previousValue != value) 
							|| (this._RoleMaster.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RoleMaster.Entity = null;
						previousValue.Cts_User_Masters.Remove(this);
					}
					this._RoleMaster.Entity = value;
					if ((value != null))
					{
						value.Cts_User_Masters.Add(this);
						this._um_RoleId = value.RoleID;
					}
					else
					{
						this._um_RoleId = default(Nullable<int>);
					}
					this.SendPropertyChanged("RoleMaster");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cts_Packages(Cts_Package entity)
		{
			this.SendPropertyChanging();
			entity.Cts_User_Master = this;
		}
		
		private void detach_Cts_Packages(Cts_Package entity)
		{
			this.SendPropertyChanging();
			entity.Cts_User_Master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cts_BranchMaster")]
	public partial class Cts_BranchMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bm_branchCode;
		
		private string _bm_branchName;
		
		private System.Nullable<bool> _bm_IsActive;
		
		private System.Nullable<int> _bm_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbm_branchCodeChanging(int value);
    partial void Onbm_branchCodeChanged();
    partial void Onbm_branchNameChanging(string value);
    partial void Onbm_branchNameChanged();
    partial void Onbm_IsActiveChanging(System.Nullable<bool> value);
    partial void Onbm_IsActiveChanged();
    partial void Onbm_ordersChanging(System.Nullable<int> value);
    partial void Onbm_ordersChanged();
    #endregion
		
		public Cts_BranchMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bm_branchCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int bm_branchCode
		{
			get
			{
				return this._bm_branchCode;
			}
			set
			{
				if ((this._bm_branchCode != value))
				{
					this.Onbm_branchCodeChanging(value);
					this.SendPropertyChanging();
					this._bm_branchCode = value;
					this.SendPropertyChanged("bm_branchCode");
					this.Onbm_branchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bm_branchName", DbType="VarChar(50)")]
		public string bm_branchName
		{
			get
			{
				return this._bm_branchName;
			}
			set
			{
				if ((this._bm_branchName != value))
				{
					this.Onbm_branchNameChanging(value);
					this.SendPropertyChanging();
					this._bm_branchName = value;
					this.SendPropertyChanged("bm_branchName");
					this.Onbm_branchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bm_IsActive", DbType="Bit")]
		public System.Nullable<bool> bm_IsActive
		{
			get
			{
				return this._bm_IsActive;
			}
			set
			{
				if ((this._bm_IsActive != value))
				{
					this.Onbm_IsActiveChanging(value);
					this.SendPropertyChanging();
					this._bm_IsActive = value;
					this.SendPropertyChanged("bm_IsActive");
					this.Onbm_IsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bm_orders", DbType="Int")]
		public System.Nullable<int> bm_orders
		{
			get
			{
				return this._bm_orders;
			}
			set
			{
				if ((this._bm_orders != value))
				{
					this.Onbm_ordersChanging(value);
					this.SendPropertyChanging();
					this._bm_orders = value;
					this.SendPropertyChanged("bm_orders");
					this.Onbm_ordersChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cts_Package")]
	public partial class Cts_Package : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_consignment_id;
		
		private System.Nullable<System.DateTime> _pk_Accept_Date;
		
		private System.Nullable<double> _pk_Package_weight;
		
		private System.Nullable<double> _pk_cost;
		
		private string _pk_Sender_address;
		
		private string _pk_Receiver_address;
		
		private string _pk_package_type;
		
		private string _pk_Employee_id;
		
		private System.Nullable<int> _pk_Customer_id;
		
		private string _pk_Current_location;
		
		private string _pk_Package_Status;
		
		private System.Nullable<bool> _pk_isActive;
		
		private System.Nullable<System.DateTime> _pk_Add_Date;
		
		private EntityRef<Cts_User_Master> _Cts_User_Master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_consignment_idChanging(int value);
    partial void Onpk_consignment_idChanged();
    partial void Onpk_Accept_DateChanging(System.Nullable<System.DateTime> value);
    partial void Onpk_Accept_DateChanged();
    partial void Onpk_Package_weightChanging(System.Nullable<double> value);
    partial void Onpk_Package_weightChanged();
    partial void Onpk_costChanging(System.Nullable<double> value);
    partial void Onpk_costChanged();
    partial void Onpk_Sender_addressChanging(string value);
    partial void Onpk_Sender_addressChanged();
    partial void Onpk_Receiver_addressChanging(string value);
    partial void Onpk_Receiver_addressChanged();
    partial void Onpk_package_typeChanging(string value);
    partial void Onpk_package_typeChanged();
    partial void Onpk_Employee_idChanging(string value);
    partial void Onpk_Employee_idChanged();
    partial void Onpk_Customer_idChanging(System.Nullable<int> value);
    partial void Onpk_Customer_idChanged();
    partial void Onpk_Current_locationChanging(string value);
    partial void Onpk_Current_locationChanged();
    partial void Onpk_Package_StatusChanging(string value);
    partial void Onpk_Package_StatusChanged();
    partial void Onpk_isActiveChanging(System.Nullable<bool> value);
    partial void Onpk_isActiveChanged();
    partial void Onpk_Add_DateChanging(System.Nullable<System.DateTime> value);
    partial void Onpk_Add_DateChanged();
    #endregion
		
		public Cts_Package()
		{
			this._Cts_User_Master = default(EntityRef<Cts_User_Master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_consignment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_consignment_id
		{
			get
			{
				return this._pk_consignment_id;
			}
			set
			{
				if ((this._pk_consignment_id != value))
				{
					this.Onpk_consignment_idChanging(value);
					this.SendPropertyChanging();
					this._pk_consignment_id = value;
					this.SendPropertyChanged("pk_consignment_id");
					this.Onpk_consignment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Accept_Date", DbType="Date")]
		public System.Nullable<System.DateTime> pk_Accept_Date
		{
			get
			{
				return this._pk_Accept_Date;
			}
			set
			{
				if ((this._pk_Accept_Date != value))
				{
					this.Onpk_Accept_DateChanging(value);
					this.SendPropertyChanging();
					this._pk_Accept_Date = value;
					this.SendPropertyChanged("pk_Accept_Date");
					this.Onpk_Accept_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Package_weight", DbType="Float")]
		public System.Nullable<double> pk_Package_weight
		{
			get
			{
				return this._pk_Package_weight;
			}
			set
			{
				if ((this._pk_Package_weight != value))
				{
					this.Onpk_Package_weightChanging(value);
					this.SendPropertyChanging();
					this._pk_Package_weight = value;
					this.SendPropertyChanged("pk_Package_weight");
					this.Onpk_Package_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_cost", DbType="Float")]
		public System.Nullable<double> pk_cost
		{
			get
			{
				return this._pk_cost;
			}
			set
			{
				if ((this._pk_cost != value))
				{
					this.Onpk_costChanging(value);
					this.SendPropertyChanging();
					this._pk_cost = value;
					this.SendPropertyChanged("pk_cost");
					this.Onpk_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Sender_address", DbType="VarChar(100)")]
		public string pk_Sender_address
		{
			get
			{
				return this._pk_Sender_address;
			}
			set
			{
				if ((this._pk_Sender_address != value))
				{
					this.Onpk_Sender_addressChanging(value);
					this.SendPropertyChanging();
					this._pk_Sender_address = value;
					this.SendPropertyChanged("pk_Sender_address");
					this.Onpk_Sender_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Receiver_address", DbType="VarChar(100)")]
		public string pk_Receiver_address
		{
			get
			{
				return this._pk_Receiver_address;
			}
			set
			{
				if ((this._pk_Receiver_address != value))
				{
					this.Onpk_Receiver_addressChanging(value);
					this.SendPropertyChanging();
					this._pk_Receiver_address = value;
					this.SendPropertyChanged("pk_Receiver_address");
					this.Onpk_Receiver_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_package_type", DbType="VarChar(30)")]
		public string pk_package_type
		{
			get
			{
				return this._pk_package_type;
			}
			set
			{
				if ((this._pk_package_type != value))
				{
					this.Onpk_package_typeChanging(value);
					this.SendPropertyChanging();
					this._pk_package_type = value;
					this.SendPropertyChanged("pk_package_type");
					this.Onpk_package_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Employee_id", DbType="VarChar(8)")]
		public string pk_Employee_id
		{
			get
			{
				return this._pk_Employee_id;
			}
			set
			{
				if ((this._pk_Employee_id != value))
				{
					this.Onpk_Employee_idChanging(value);
					this.SendPropertyChanging();
					this._pk_Employee_id = value;
					this.SendPropertyChanged("pk_Employee_id");
					this.Onpk_Employee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Customer_id", DbType="Int")]
		public System.Nullable<int> pk_Customer_id
		{
			get
			{
				return this._pk_Customer_id;
			}
			set
			{
				if ((this._pk_Customer_id != value))
				{
					if (this._Cts_User_Master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpk_Customer_idChanging(value);
					this.SendPropertyChanging();
					this._pk_Customer_id = value;
					this.SendPropertyChanged("pk_Customer_id");
					this.Onpk_Customer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Current_location", DbType="VarChar(100)")]
		public string pk_Current_location
		{
			get
			{
				return this._pk_Current_location;
			}
			set
			{
				if ((this._pk_Current_location != value))
				{
					this.Onpk_Current_locationChanging(value);
					this.SendPropertyChanging();
					this._pk_Current_location = value;
					this.SendPropertyChanged("pk_Current_location");
					this.Onpk_Current_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Package_Status", DbType="VarChar(50)")]
		public string pk_Package_Status
		{
			get
			{
				return this._pk_Package_Status;
			}
			set
			{
				if ((this._pk_Package_Status != value))
				{
					this.Onpk_Package_StatusChanging(value);
					this.SendPropertyChanging();
					this._pk_Package_Status = value;
					this.SendPropertyChanged("pk_Package_Status");
					this.Onpk_Package_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_isActive", DbType="Bit")]
		public System.Nullable<bool> pk_isActive
		{
			get
			{
				return this._pk_isActive;
			}
			set
			{
				if ((this._pk_isActive != value))
				{
					this.Onpk_isActiveChanging(value);
					this.SendPropertyChanging();
					this._pk_isActive = value;
					this.SendPropertyChanged("pk_isActive");
					this.Onpk_isActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_Add_Date", DbType="Date")]
		public System.Nullable<System.DateTime> pk_Add_Date
		{
			get
			{
				return this._pk_Add_Date;
			}
			set
			{
				if ((this._pk_Add_Date != value))
				{
					this.Onpk_Add_DateChanging(value);
					this.SendPropertyChanging();
					this._pk_Add_Date = value;
					this.SendPropertyChanged("pk_Add_Date");
					this.Onpk_Add_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cts_User_Master_Cts_Package", Storage="_Cts_User_Master", ThisKey="pk_Customer_id", OtherKey="um_id", IsForeignKey=true)]
		public Cts_User_Master Cts_User_Master
		{
			get
			{
				return this._Cts_User_Master.Entity;
			}
			set
			{
				Cts_User_Master previousValue = this._Cts_User_Master.Entity;
				if (((previousValue != value) 
							|| (this._Cts_User_Master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cts_User_Master.Entity = null;
						previousValue.Cts_Packages.Remove(this);
					}
					this._Cts_User_Master.Entity = value;
					if ((value != null))
					{
						value.Cts_Packages.Add(this);
						this._pk_Customer_id = value.um_id;
					}
					else
					{
						this._pk_Customer_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cts_User_Master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
